---

# NOTE: running `nvm version default` or `nvm version lts/gallium` returns `v16.14.2`
default_node_version_name: lts/gallium # 16.x

node_packages_to_install_globally:
  - create-react-app # create react apps with no build configuration
  - npm-quick-run # quickly run npm script by prefix without typing the full name
  - npmrc # switch between different .npmrc files with ease and grace

# https://github.com/nodejs/Release
# https://github.com/nodejs/Release#release-schedule
# https://github.com/nvm-sh/nvm#long-term-support
# https://nodejs.org/download/release/latest-v6.x/
# https://nodejs.org/download/release/latest-v8.x/
# https://nodejs.org/download/release/latest-v10.x/
# https://nodejs.org/download/release/latest-v12.x/
# https://nodejs.org/download/release/latest-v14.x/
# https://nodejs.org/download/release/latest-v16.x/
# no lts versions exist for 7.x, 9.x, 11.x, 13.x, 15.x, 17.x
# [$]> nvm ls
# [$]> nvm ls-remote
# [$]> nvm ls-remote --lts | grep Latest
#   v4.9.1   (Latest LTS: Argon)
#  v6.17.1   (Latest LTS: Boron)
#  v8.17.0   (Latest LTS: Carbon)
# v10.24.1   (Latest LTS: Dubnium)
# v12.22.7   (Latest LTS: Erbium)
# v14.18.2   (Latest LTS: Fermium)
# v16.13.1   (Latest LTS: Gallium)
node_versions_to_install: # last checked for updates on 12/13/2021
  - lts/dubnium # 10.x
  - lts/erbium # 12.x
  - lts/fermium # 14.x
  - lts/gallium # 16.x

# node.js 14 will be the `current` release for the next 6 months, and then promoted to long-term support (lts) in october 2020
# both node.js 12 and node.js 10 will remain in long-term support until april 2022 and april 2021 respectively
