---

# [$]> defaults read -g com.apple.trackpad.scaling
# [$]> defaults write -g com.apple.trackpad.scaling 60
- name: role [{{ role_name }}] increase trackpad tracking speed "trackpad -> point & click -> tracking speed"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    value: 60
# fatal: [0.0.0.0]: FAILED! => {"changed": false, "msg": "Type mismatch. Type in defaults: str"}
# [$]> defaults read-type -g com.apple.trackpad.scaling
# Type is string
