---

- hosts: localhost
  connection: local

  vars_files:
    - vars.private.yml

  roles:
    - role: brew
      tags: ['brew']
    - role: defaults
      tags: ['defaults']
    - role: sublime
      tags: ['sublime']
    - role: vim
      tags: ['vim']
    - role: node
      tags: ['node']
    - role: app_store
      tags: ['app_store']
    - role: dock
      tags: ['dock']
    - role: git
      tags: ['git']
    - role: shell
      tags: ['shell']

  tasks:
    - name: display message
      debug:
        msg: 'Playbook Is Finished Running!'
