---

- hosts: localhost
  connection: local

  vars_files:
    - vars.private.yml

  roles:
    - role: brew
      tags: ['brew']
    - role: node
      tags: ['node']
    - role: app_store
      tags: ['app_store']

  tasks:
    - name: display message
      debug:
        msg: 'Playbook Is Finished Running!'
