---

# NOTE: switched to a cask that was rewritten in swift to fix the following error
# [$]> brew install --cask hpedrorodrigues/tools/dockutil
# https://github.com/hpedrorodrigues/homebrew-tools/blob/master/Casks/dockutil.rb
# https://github.com/kcrawford/dockutil/issues/127
# https://github.com/kcrawford/dockutil/issues/111
# https://github.com/kcrawford/dockutil/issues/85
# /bin/sh: /usr/local/bin/dockutil: /usr/bin/python: bad interpreter: No such file or directory

- name: role [{{ role_name }}] remove all items from the dock
  shell: dockutil --remove all --no-restart

- name: role [{{ role_name }}] set the default dock items
  shell: dockutil --add {{ item }} --no-restart
  with_items: "{{ dock_items }}"

- name: role [{{ role_name }}] reduce the size of the dock
  shell: defaults write com.apple.dock tilesize -int 30

- name: role [{{ role_name }}] disable showing recently opened apps
  shell: defaults write com.apple.dock show-recents -bool false

- name: role [{{ role_name }}] enable dock's auto hide feature
  shell: m dock autohide YES

- name: role [{{ role_name }}] disable automatically rearrange spaces based on most recent use
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false

- name: role [{{ role_name }}] reset launchpad
  osx_defaults:
    domain: com.apple.dock
    key: ResetLaunchPad
    type: bool
    value: true

# need to restart the dock after disabling the dashboard
- name: role [{{ role_name }}] disable the dashboard
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true

- name: role [{{ role_name }}] restart dock
  shell: killall Dock
