---

# [$]> brew install dockutil
- name: role [{{ role_name }}] install packages
  homebrew:
    name: '{{ brew_packages }}'
    state: latest
  tags:
    - install_brew

# [$]> brew install --cask sublime-text
- name: role [{{ role_name }}] install cask packages
  homebrew_cask:
    name: '{{ brew_cask_packages }}'
    state: latest
  tags:
    - install_casks
