---

# brew update is for updating homebrew (downloads new "formulae" but won't upgrade the installed software)
- name: role [{{ role_name }}] update homebrew
  homebrew:
    update_homebrew: yes
  tags:
    - brew_update

# Error:
#   homebrew-core is a shallow clone.
#   homebrew-cask is a shallow clone.

# To `brew update`, first run:
#   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
#   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow

# This restriction has been made on GitHub's request because updating shallow
# clones is an extremely expensive operation due to the tree layout and traffic of
# Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
# automatically to avoid repeatedly performing an expensive unshallow operation in
# CI systems (which should instead be fixed to not use shallow clones). Sorry for
# the inconvenience!

# brew upgrade is for updating installed software
- name: role [{{ role_name }}] upgrade homebrew
  homebrew:
    upgrade_all: yes
  tags:
    - brew_upgrade
