---

# [$]> brew install mas
- name: role [{{ role_name }}] install packages
  homebrew:
    name: '{{ brew_packages }}'
    state: latest
  tags:
    - install_brew

# NOTE: Running installer for dockutil; your password may be necessary.
# [$]> brew install --cask sublime-text
- name: role [{{ role_name }}] install cask packages
  homebrew_cask:
    name: '{{ brew_cask_packages }}'
    state: latest
  tags:
    - install_casks
